In [ ]:
from datasets import load_dataset
datasets = load_dataset("./wisesight_sentiment", trust_remote_code=True)

In [2]:
train_df = datasets['train'].to_pandas()
val_df = datasets['validation'].to_pandas()
test_df = datasets['test'].to_pandas()

In [3]:
# Using a mapping dictionary
mapping = {
    0: "positive",
    1: "neutral",
    2: "negative"
}

In [4]:
train_df["label"] = train_df["category"].apply(lambda x: mapping.get(x, "q"))
train_df = train_df[train_df['label'] != 'q'].reset_index(drop=True)

val_df["label"] = val_df["category"].apply(lambda x: mapping.get(x, "q"))
val_df = val_df[val_df['label'] != 'q'].reset_index(drop=True)

test_df["label"] = test_df["category"].apply(lambda x: mapping.get(x, "q"))
test_df = test_df[test_df['label'] != 'q'].reset_index(drop=True)

In [5]:
train_sample = train_df.drop_duplicates().sample(n=10000, random_state=42)
val_sample = val_df.drop_duplicates().sample(n=1000, random_state=42)
test_sample = test_df.drop_duplicates().sample(n=2000, random_state=42)

In [6]:
SYSTEM_PROMPT = """You are an AI assistant specialized in social sentiment analysis.
Your task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:

positive: The text expresses favorable, supportive, or happy emotions.
negative: The text expresses unfavorable, critical, or unhappy emotions.
neutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.
"""

In [7]:
print(SYSTEM_PROMPT)

You are an AI assistant specialized in social sentiment analysis.
Your task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:

positive: The text expresses favorable, supportive, or happy emotions.
negative: The text expresses unfavorable, critical, or unhappy emotions.
neutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.

In [8]:
train_sample.head()

                                                   texts  category     label
640                                    19 ปีเข้าได้ไหมคะ         1   neutral
11990                                         ถ้าหายดีนะ         0  positive
5990   มันคือเรฟลอน โฟโต้เรดดี้ แอร์บลัช เอฟเฟ็ค เมคอ...         1   neutral
16887                                    ไทยแม้งหัวโบราณ         2  negative
12783                                        แดกให้ตายไป         1   neutral

In [9]:
val_sample.head()

                                                  texts  category     label
1138                        เพราะกลัวมาสด้า 3 ขายไม่ออก         2  negative
1628              อยากกินเหมือนกันนนน อยากกินทุกอย่างงง         0  positive
1606  (ตัวช่วยที่จะให้สาวๆแต่งหน้าสวยมากยิ่งขึ้น) มี...         0  positive
1976  กินมาจนนับขวดไม่ได้ของเขาดีจริง. รูปโปรฟายยังเ...         0  positive
1526                                       สู้ครับผมๆๆๆ         0  positive

In [10]:
test_sample.head()

                                                  texts  category     label
2437                  เริ่มปีใหม่ด้วยคิง 4 ตาติด เริศ!!         0  positive
1033  เพิ่มอะเซทิล แอลคาร์นิทีน ให้กับร่างกาย เเละ ส...         1   neutral
2575  วันนี้​ไปกินถามว่าอร่อยครับแต่บางพนักงาน​ก้ไม่...         2  negative
1124  หิวมะไหร่ก้แวะมาที่เซเว่น อีเลฟเวน ตึ่ง!! อ่าว...         1   neutral
1942  โปรโมชั่นยังมีอยู่ค่ะ แต่ราคาผ่อนเริ่มต้นจะเป็...         1   neutral

In [11]:
[
  {
    "messages": [
      {
        "role": "system",
        "content": "system prompt (optional)"
      },
      {
        "role": "user",
        "content": "user instruction"
      },
      {
        "role": "assistant",
        "content": "model response"
      }
    ]
  }
]

[{'messages': [{'role': 'system', 'content': 'system prompt (optional)'},
   {'role': 'user', 'content': 'user instruction'},
   {'role': 'assistant', 'content': 'model response'}]}]

In [20]:
train_data_openai_format = []
val_data_openai_format = []
test_data_openai_format = []

In [21]:
for row in train_sample.iterrows():
    train_data_openai_format.append(
        {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": row[1]['texts']
            },
            {
                "role": "assistant",
                "content":  row[1]['label']
            }
        ]}
    )

In [22]:
for row in val_sample.iterrows():
    val_data_openai_format.append(
        {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": row[1]['texts']
            },
            {
                "role": "assistant",
                "content":  row[1]['label']
            }
        ]}
    )

In [23]:
for row in test_sample.iterrows():
    test_data_openai_format.append(
        {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": row[1]['texts']
            },
            {
                "role": "assistant",
                "content":  row[1]['label']
            }
        ]}
    )

In [24]:
train_data_openai_format

[{'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': '19 ปีเข้าได้ไหมคะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ถ้าหายดีนะ'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'มันคือเรฟลอน โฟโต้เรดดี้ แอร์บลัช เอฟเฟ็ค เมคอัพ ทุกเฉด คูปองลดทันที 100 บาท ในโปรโมชั่น Watsons Beauty in Summer (29 มี.ค. - 25 เม.ย. 61) เจ้าค่ะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ไทยแม้งหัวโบราณ'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'แดกให้ตายไป'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'ตอนเบียร์ช้างจะลงตลาดหุ้นไทย หมาตัวไหนคัดค้านครับ สุดท้ายย้ายไปสิงคโปร์ ใครได้ประโยชน์? สุดท้าย รง.ผลิตก็อยู่เมืองไทย แต่เราไม่ได้ภาษีหุ้น จบปิ้ง'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'มีใจก็ตามมา จะหนีใครมาก็ตามใจ🙃 U beer เบียร์ของคุณ เบียร์ในแบบที่เป็นตัวคุณ #ubeer'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'พื้นเหมือนจะสะอาดเพราะเป็นหินอ่อนแต่พอลองเดินเท่านั้นแหละเท้าดำเลย'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'อัลเมร่า อี สปอด ส่ง 6800×84 งวดครับ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'Aqua มันให้ถึง300ล้านเลยหรอ Sigha comperation รึป่าวครับท่าน เบียร์สิงห์ เครือสิงห์อ่ะ รู้จักไหม'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': '#ถ้ารู้จักจะรักแน่นอน 💖💖 #อ่านก่อนชะลอวัยอ่านจบไวสุขภาพดี 💢💢 #กู้ร่างกลับฉบับชะลอวัย ✌✌ #หนังสือสุขภาพมาแรงที่ใครๆก็มี 👈👈 #เปิดใจแล้วเปิดอ่านสิ่งชื่นบานจะตามมา 😉😗'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'น้องบาร์บีก้อน น้องโรเซ่ น้องโฮการ์เด้น 555+'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เดี๋ยวมรึงโดน!!!! เหลวไหล'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'อยากได้ค่ะ 😁'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ขอรายละเอียด X-Trail ครับ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'อดีตเคยหลงรักป๋องดำ ปัจจุบันต้องป๋องน้ำเงินคาดแดงนี้จริงๆ อดีตก็คืออดีต เราจะไม่หันหลังกลับ #kuเลิฟ #รีวิวเซเว่น #kulovmax7'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'พี่บลูมาเวรไหนก็ฝากเวรนั้นเยย'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': '555555 จะหิวแล้วววว'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'Honda city v+ สนใจ'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'จัดเลย😆😆'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เช่นถ้าคนติดคุกเพราะเสพกัญชา แล้วถ้ามีการแก้กฎหมายว่ากัญชาไม่ใช่สิ่งเสพติด คนที่ติดคุกเพราะกัญชาก็ต้องถูกปล่อยตัวครับ แต่กรณีบุหรี่ไฟ้าเป็นการปรับหรือยึดของ ยังไงก็ต้องคืนของครับ ส่วนค่าปรับไม่แน่ใจครับว่าจะคืนได้มั้ย'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เตรียมพบกับ ใหม่! อีซูซุดีแมคซ์เอ็กซ์-ซีรี่ส์ แรงสุดขีด...เต็มสปีดพันธุ์เอ็กซ์ THE X-SPIRIT OUTBURST'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'ใหม่นิสสันนาวาร่ากับก้องรอบทิศไร้กังวลเลยแบบนี้'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'จริงค่ะ คันเก่า วีออส ซิ้อป้ายแดงมาขับนาน 10 ปี ใส่น้ำยาหม้อน้ำตลอดไม่มีปัญหา เพราะรถใหม่ ถ้าเป็นรถเก่าช่างจะไม่แนะนำให้ใช้ เพราะ จะทำให้หม้อน้ำเป็นรังผึ้ง ช่างแนะนำว่าใช้ได้เฉพาะรถใหม่ค่ะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ถ้ามีตังหน่อย ก็ไฮเนเก้น .... #เดี๋ยวววว'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ตำรวจของขาด'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'หมอบางปิมียะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ได้หมด ถ้าโบนัสออก'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เพจ สังคมอักเสบ ก้ออกมาโจมตี'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'อยู่ในเมือง หายากหน่อยถ้าไม่มี googlemap เก่าโทรม renovate เฉพาะจุดเลยทำให้สภาพเหมือนจะใหม่ก็ไม่ใหม่ กึ่งเก่ากึ่งใหม่ ห้องน้ำโทรม ตัวห้องดูใหม่'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',

In [25]:
len(train_data_openai_format)

10000

In [26]:
val_data_openai_format

[{'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เพราะกลัวมาสด้า 3 ขายไม่ออก'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'อยากกินเหมือนกันนนน อยากกินทุกอย่างงง'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': '(ตัวช่วยที่จะให้สาวๆแต่งหน้าสวยมากยิ่งขึ้น) มีรองพื้นสูตรใหม่แล้ว ไพรเมอร์สูตรใหม่ต้องมีเช่นกันค่ะ ไพรเมอร์ที่ทางทาง YSL เค้าเคลมว่า การันตีความแมทท์ยาวนาน พร้อมคุมมันในทันที ทำให้รูขุมขนแลดูเล็กลง ด้วยเนื้อครีมที่บางเบา ช่วยให้ผิวเรียบเนียนขึ้นในทันที'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'กินมาจนนับขวดไม่ได้ของเขาดีจริง. รูปโปรฟายยังเป็นช้างเลย'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'สู้ครับผมๆๆๆ'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ป่ะ บาบีกอน บุฟเฟ่คิดถึงเซลมอล กับน้ำจิ้ม'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เบียร์ช้าง'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'พนักงานไม่มีมารยาทมาก แย่มากมากินก็เสียเงิน มีโปรโมทอะไรก็เหมือนไม่อยากจะอธิบาย สาขาแฟชั่น ถ้าเปลี่ยนนิสัยไม่ได้แนะนำให้เปลี่ยนพนักงานนะคะทำนิสัยแบบนี้ไล่ลูกค้าชัดๆ แล้วก็ให้หมูดูน้อยๆด้วย รู้สึกไม่คุ้มแต่ก็กิน'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': '“โรงแรมดุสิตธานี กรุงเทพฯ” เป็นโรงแรมเก่าแก่แห่งหนึ่งของเมืองไทย เริ่มก่อสร้างในปี พ.ศ. 2509 โดยบริษัท ดุสิตธานี จำกัด ตัวอาคารก่อสร้างในลักษณะทรงสูง 22 ชั้น วัดจากพื้นดินไปถึงปลายยอดสูงสุด 100 เมตร ตั้งอยู่บนเนื้อที่ 16 ไร่ หัวมุมถนนสีลม ตรงข้ามกับสวนลุมพินี กรุงเทพฯ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ไม่ไหวแล้วอยากฆ่าพี่ก้อน'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'ฉลอง New Year Party กันเองง่ายๆ แบบพี่ๆ น้องๆ ครอบครัวสิงห์ เมื่อคืนที่ผ่านมา #est33 #est33bysingha #estcareterings #craftbeer #singhaallstar #cdc #party'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ชงๆชีสๆไร 🙄'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'หิววววเลย'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'Honda หากดัดแปลงเป็น Taxi BSI ขาดทันทีถึงแม้จะซื้อสดก็ตาม'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'สงสัยชอบกินลีโอมากกว่าสิงห์ 😢'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ok เย้ๆๆ ผึ้งเลี้ยงงง'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ลองดิ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เหม็นบุหรี่ไฟฟ้าว้อยยย ปวดเมนส์ด้วย แงงงง 😢😭'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เกี๊ยวหมดแล้วยังไงอ่ะ ก็หมดไปซิ อย่างนั้นเหรอ ง่ายไปไหม???'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'บ่ายๆ พี่ก้อนำเสนอนะคะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'อยากให้ทุกคนได้ดูรูปนี้ สรุปออกมาดีมากๆ • กรอบสีแดงกับส้มคือ ”ไม่สนับสนุนเผด็จการ(คสช.)” • เขียวคือ ”สนับสนุนเผด็จการสืบทอดอำนาจ” • น้ำเงินคือ “พร้อมแปรพักตร์ตลอดเวลา” สรุปง่ายๆคือ ถ้าเราเลือกพรรคกรอบแดงกับส้มมากพอ ประยุทธ์และคสช.จะไม่มีทางได้เป็นรัฐบาลอีก #เลื่อนแม่มึงสิ'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เจมสัน 5555555'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'สาขาที่ร่วมรายการมีดังนี้ค่ะ - บิ๊กซี โคราช - โลตัส โคราช 1 - เดอะมอล์ล โคราช - โลตัส โคราช 2 (หัวทะเล) - บิ๊กซี โคราช 2 - โลตัส พิมาย นครราชสีมา - บิ๊กซี สีคิ้ว โคราช ^^'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'ทายสิว่า อิชั้นกินร้านไหน บอกเลย #เสียฟามรู้สึกกับแมคมาก'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เป็นคนผิวหน้ามันและรูขุมขนกว้าง ผิวมันแต่ขาดน้ำ วันไหนไม่ได้แต่งหน้าคือ หน้าสดไม่รอดค่ะ😅 แต่ยังโชคดีที่มาเจอน้ำตบLife Plankton ของBiotherm ใช้ขนาดทดลองมา2ขวดเอง รู้สึกว่าผิวหน้าชุ่มชื้น ผิวใสขึ้นมาก นี่ขนาดใช้ในปริมาณเล็กน้อยเท่านั้นนะคะ ผลลัพธ์ปลื้มมาก ช่วงมีสิว ตบน้ำตบก่อนนอนตื่นมาสิวยุบ เลยอยากได้ AQUASOURCE AURA มาเป็นคู่ซี้อีกตัว จะได้เปิดเผยหน้าสดแบบไม่อายบ้างค่ะ😘 #Beautygalerie #CentralDepartmentstore #BIOTHERMTHAILAND #AQUASOURCEAURA #หน้าสดแต่ไม่เศร้า'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ปัตตานี'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'มิตซู เตชอัมพร (แยกบางแพ) ขอเชิญทุกท่านเที่ยวงาน Mini Motor Show @ งานกาชาดราบุรี ร่วมสัมผัสและทดลองขับยนตรกรรมชั้นนำจาก มิตซูบิชิ ทั้ง 4 รุ่น ได้แก่ ปาเจโร สปอร์ต, ไทรทัน, แอททราจ , มิราจ และยังได้ใกล้ชิดกับ MC ชั้นแนวหน้าของเมืองไทย และ พริตตี้ตัวท๊อปติดอันดับ 1 ใน 10 จากมอเตอร์โช์ ชมการแสดงโชว์ล้างรถจากพริตตี้ สาว สวย sexy และ โชว์พิเศษจากแชมป์โคโยตี้ประเทศไทย นินิวเอวเด้ง พร้อมรับข้อเสนอสุดพิเศษ เงื่อนไขเดียวกับงานมอเตอร์โชว์ อีกเพียบ พบกันที่บูธของมิตซูบิชิ โดย มิตซูเตชอัมพร ตั้งแต่วันที่ 24 มีนา-1 เมษา 61 นี้ นะค่ะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'ส่วนตัวเฉยๆกับการไม่ให้ถุงมาก เพราะอยู่มหิดล เซเว่น แฟมิลี่ ร้านในมอไม่เคยให้ถุงเล๊ยยยย ไม่ว่าจะซื้อของเยอะ หมดไปหลายร้อยแค่ไหน ให้เพื่อนช่วยหอบกันขึ้นหอค่ะ555555'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',

In [27]:
len(val_data_openai_format)

1000

In [28]:
test_data_openai_format

[{'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เริ่มปีใหม่ด้วยคิง 4 ตาติด เริศ!!'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เพิ่มอะเซทิล แอลคาร์นิทีน ให้กับร่างกาย เเละ สมอง ✨ สารอาหารชะลอวัยระดับเซลล์ ซ่อมแซมสมอง ป้องกันอัลไซม์เมอร์ ☘️☘️| ไทยธรรม อัลไลแอนซ์ ผู้นำนวัตกรรมสุขภาพและความงาม คลิ๊กที่นี่ >>http://www.thaidham.com/articles/product/wisma'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'วันนี้\u200bไปกินถามว่าอร่อยครับแต่บางพนักงาน\u200bก้ไม่ค่อยใส่ใจเท่าไร\u200b ผมค้องการพริกกับกะเทียมเพิ่มไปวางข้างเยือกโค๊กผมนึกว่าพนักงานจะรุ้แต่ป่าวเลยเดินไปเดินมสไม่สนใจจนผมต้องเปิดฝาก้ยังเดินผ่านไปผ่านทำไมสนใจเหมือนเดิมจ่ายเงินเสดให้เบิลมาดรอกข้อมูล\u200bพนักงานมสยืนจ้อง\u200bข้างคือเขาจะให้เขียนพนักไม่สนใจดูแลลูกค้าคนก้ไม่ได้เยอะแยะ\u200bอะไรทำไมต้องยืนจ้องขนาดนั้น'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'หิวมะไหร่ก้แวะมาที่เซเว่น อีเลฟเวน ตึ่ง!! อ่าว นี่มัน MK'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'โปรโมชั่นยังมีอยู่ค่ะ แต่ราคาผ่อนเริ่มต้นจะเป็น 9,xxx บาท (ไม่ใช่ 9,000 บาทถ้วนค่ะ ต้องขออภัยในความไม่สะดวก อยู่ในระหว่างการดำเนินการแก้ไขบนเว็บไซด์ค่ะ) ฟรี ประกันภัย ชั้น 1 ดอกเบี้ย 1.74%* สำหรับลูกค้าเก่าฮอนด้า ซื้อ Super Pack ประกันภัยชั้น 1 2 ปี เฉพาะบริษัทประกันภัยที่ร่วมรายการในราคาพิเศษ 8,000 บาท'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เคยเก็บฝาเบียร์ช้างเพื่อแลกกับการเข้าชมคาราบาวตอนเด็กๆ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ยุ่ง'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'วันเสาร์ได้ไหมพี่555'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'วันศุกร์ที่ 9 มีนาคมนี้ เตรียมพบกับ Suyano ดีเจหนุ่มชาวดัตช์ สไตล์ Progressive และ Electro House กับความสามารถอันโดดเด่นในผลงานเพลงเช่น “Switch up” Suyano ได้รับเลือกให้อยู่ในอันดับที่ 29 จากการจัดอันดับโดย Beatport ในสาขา Best Selling Artist in Beatport Bigroom Charts อีกด้วย เตรียมระเบิดความมันส์ ไปกับ Suyano ได้ในวันที่ 9 มีนาคมนี้ ที่ DEMO 20+bring Id. party by CLAP & Bacardi more info please call 088-888-8888 02-2222222 English service 099-999-9999'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'มีความเป็น ซีวิค..'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'ไม่absoluteละ vodkaมันอ่อนไป absintheเลยเถอะ'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'วัดไล่ที่ชาวบ้านด้วย แอบขายที่ธรณีสงฆ์ให้กทม.+สำนักงานทรัพย์สิน. อ้างหาเงินบำรุงวัด สร้างศาสนาสถานเพื่อชาติ ท่องเที่ยว'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'อยากดู เทียน่า2011สีขาวพอจะมีไหมครับ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เก็บตังไปกินกัน555'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'อยากให้มีเมนูใหม่ๆบ้างนะครับกินมานานนนนนนมากจับอันในใส่อันนี้ไม่มีความแปลกใหม่ขึ้นมาเลย(ขออภัยถ้าข้อความนี้รบกวนลบได้นะครับจากครอบครัวที่กินเอ็มเคทุกสัปดาห์มาสิบปีอยากมีอะไรใหม่ๆให้กินบ้าง)'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'มะกรุก สามตะกร้า ไปกัน'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'คนไทยต้องซีวิคครับ ไม่งั้นไม่เท่'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เล่นน้ำแบบไม่กลัวแดด เพราะ บีโอเร เป็นครีมกันแดดที่มี spf 50 ++++ ซึมเข้าสู่ผิวได้ดี ไม่เหนียวเหนอะหนะไม่เป็นคราบ และกันแดด กันน้ำได้ดี ไม่ว่าแดดจะแรงแค่ไหนก็มั่นใจได้ตลอดทั้งวัน #BioreUVEssence #BioreFunlnTheSun #SongkgkranFunFest #กันแดดกันแก่ที่ดีที่สุด #กันแดดอันดับ1จากญี่ปุ่น'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'เลื่อนอ่านอยุ่หลายสิบเม้น เจอเม้นนี้ไม่แวะคงไม่ได้ ถ้าผมขับวีโก้นี่เผลอๆมีขายทิ้ง5555'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'เบียร์สิงห์ไปไหน'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': '.1.แป้ง Arty 2.ครีมกันแดด 3.น้ำยาถูพื้น 4.เครื่องทำวาฟเฟิล 5.KMA ลิปสติก-------'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': '555555 ขนาดนั่นเลย'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'น่ากินดีอ่ะพี่'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'แง บาบีก้อนนนนนนนนนนนนน ถ้ามีไข่พยาธิน้องไม่โอเคคคคคคคคคคคคค'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'สองคนหะน่ะ'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user',
    'content': 'พรีเมี่ยม หรูหรา มีระดับ ราคาแบบนี้ จัดไปครับ! #TeamRoyal #มีดีมากกว่าหน้าตา'},
   {'role': 'assistant', 'content': 'positive'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': 'จานใหญ่จริงๆ😒 ใหญ่แต่จานจริงๆ☹️ #mk'},
   {'role': 'assistant', 'content': 'negative'}]},
 {'messages': [{'role': 'system',
    'content': 'You are an AI assistant specialized in social sentiment analysis.\nYour task is to classify the sentiment expressed in a given piece of text from social media into one of the following categories:\n\npositive: The text expresses favorable, supportive, or happy emotions.\nnegative: The text expresses unfavorable, critical, or unhappy emotions.\nneutral: The text expresses neither positive nor negative sentiment, or it is objective, factual, or ambiguous.\n'},
   {'role': 'user', 'content': '!! * เทอร์โบใหญ่ ❤'},
   {'role': 'assistant', 'content': 'neutral'}]},
 {'messages': [{'role': 'system',

In [29]:
len(test_data_openai_format)

2000

In [31]:
import pandas as pd

In [40]:
pd.DataFrame(train_data_openai_format).to_json('./wisesight_process/wongnai_sentiment_train.json',
                                            lines=True, orient='records', force_ascii=False)
pd.DataFrame(val_data_openai_format).to_json('./wisesight_process/wongnai_sentiment_val.json',
                                            lines=True, orient='records', force_ascii=False)
pd.DataFrame(test_data_openai_format).to_json('./wisesight_process/wongnai_sentiment_test.json',
                                            lines=True, orient='records', force_ascii=False)